### ISSUE TITLE
[FR] YAML property with autoscroll speed

### ISSUE THREAD

**Issue by hyungtaecf** [olvidalo/obsidian-chord-sheets#1]
I suggest to name a property to set the autoscroll speed. This is useful to set it to each note differently, so they scroll differently according to the tempo for each song (note).

This is how it would look like:
```yml
---
autoscroll-speed: 6
---
```

So, if the note contains this property it would override the "default auto-scroll speed" to that value when it is inside that note.

ps: Btw this is a great plugin, thanks for your effort :)

**Comment by olvidalo** [comment]
Seems like a useful suggestion, I'll have a look at it.

Glad you like the plugin!
