### ISSUE TITLE
BUG - Transpose just after changing Instrument

### ISSUE THREAD

**Issue by emnik** [olvidalo/obsidian-chord-sheets#13]
Hi! Bravo for your incredible work!

There is a bug where if I try to transpose just after changing the instrument everything brakes...
can you confirm it on your side?

**Comment by olvidalo** [comment]
Can confirm, strange things happen when transposing after changing instrument. Thanks for reporting, will look into this.

**Comment by olvidalo** [comment]
Fixed in the latest release
