### ISSUE TITLE
Doesn't Work At All

### ISSUE THREAD

**Issue by jpfieber** [olvidalo/obsidian-chord-sheets#14]
Running most recent Obsidian on Windows 11. The code block doesn't seem to get processed properly. I left the settings all at default.  I insert a code block with the default 'cords', but nothing happens:
![image](https://github.com/user-attachments/assets/97e8761d-0795-4c94-a64e-1cfff1662c16)
![image](https://github.com/user-attachments/assets/a9a2792f-f21d-4271-95f2-f2f3752c91c6)
When I move over text in the box, I do see a hint with a number in it.
![image](https://github.com/user-attachments/assets/1eaacb43-907a-487f-8160-115735d28623)
I also see in the console that things are being done:
![image](https://github.com/user-attachments/assets/7db30d14-176e-458d-bd08-b154d9da767b)
I disabled all plugins to remove the chance of a conflict, but no change.
I usually work in Preview mode, but doesn't work in Reading view as well.
Help!

**Comment by olvidalo** [comment]
Try ```chords, with an h after the c :)

**Comment by jpfieber** [comment]
<embarrassed>I figured it would be something simple. Thanks for creating such a cool, useful plugin!</embarrassed>
