### ISSUE TITLE
Chord overview is always visible in reading view

### ISSUE THREAD

**Issue by mikefowler** [olvidalo/obsidian-chord-sheets#16]
Thank you, @olvidalo, for a really beautiful Obsidian extension!

After installing the plugin, I am noticing that the "Show chord overview" setting does not seem to work as expected. I currently have it set to "Never," and though the chord overview does not show up in edit mode, it is still showing up in reading mode.

**Comment by olvidalo** [comment]
Thanks for pointing this out! Fixed in the latest release.
