### ISSUE TITLE
Chords don't renderized

### ISSUE THREAD

**Issue by thiagoalcav** [olvidalo/obsidian-chord-sheets#4]
Hi, first of all, congratulations for this project! It's awesome! I use it with Obsidian for a while and I realize that some chords don´t recognized. i.e:  C7M, Bb7M, Gm7(9), F7M, A4(5+)... 

Only simple chords are renderized correctly:

- ![image](https://github.com/user-attachments/assets/11e9e530-422d-45f3-948e-975359582aa6)

Is there other way to write those chords?

**Comment by thiagoalcav** [comment]
I Realize that soma abbreviations works, like this page shows: 
- https://www.scales-chords.com/chord/guitar/Bb7M

**Comment by olvidalo** [comment]
Thanks for reporting! Those notations don't seem very common but let's see if these can be supported. I tried to identify more common notations for these chords (such as Bbmaj7 for Bb7M/BbM7), could you please confirm that these are the correct equivalents:

* **C7M**: [CM7 / Cmaj7](https://jguitar.com/chordsearch?chordsearch=Cmaj7&labels=none) (C with major 7th)
* **F7M**: [CM7 / Cmaj7](https://jguitar.com/chordsearch?chordsearch=Fmaj7&labels=none) (F with major 7th)
* **Gm7(9)**: [Gm9 / Gm7add9](https://jguitar.com/chordsearch?chordsearch=Gm7add9&labels=none) (G minor with minor 7th and added 9th)
* **A7(5+)**: [A7#5](https://www.all-guitar-chords.com/chords/index/a/7*5) (A with minor 7th and augmented 5th)
* **A4(5+)**: [Asus4#5](https://jguitar.com/chordsearch/Asus4%235) (A with suspended 4th and raised 5th)

**Comment by thiagoalcav** [comment]
> Obrigado por reportar! Essas notações não parecem muito comuns, mas vamos ver se elas podem ser suportadas. Tentei identificar notações mais comuns para esses acordes (como Bbmaj7 para Bb7M/BbM7), você poderia confirmar se esses são os equivalentes corretos:
> 
> * **C7M** : [CM7 / Cmaj7](https://jguitar.com/chordsearch?chordsearch=Cmaj7&labels=none) (C com 7ª maior)
> * **F7M** : [CM7 / Cmaj7](https://jguitar.com/chordsearch?chordsearch=Fmaj7&labels=none) (Fá com sétima maior)
> * **Gm7(9)** : [Gm9 / Gm7add9](https://jguitar.com/chordsearch?chordsearch=Gm7add9&labels=none) (sol menor com sétima menor e 9ª adicionada)
> * **A7(5+)** : [A7#5](https://www.all-guitar-chords.com/chords/index/a/7*5) (A com 7ª menor e 5ª aumentada)
> * **A4(5+)** : [Asus4#5](https://jguitar.com/chordsearch/Asus4%235) (A com 4ª suspensa e 5ª elevada)

Exatatamente essas!
