### ISSUE TITLE
Better tabulature support

### ISSUE THREAD

**Issue by JoeKays** [olvidalo/obsidian-chord-sheets#5]
Hi,

first of all, thank you for the great plugin. Especially the auto-scroll feature is super useful!

The only problem I have with it is that the matching is a bit too fuzzy, e.g. slides in tabulatures are recognized as chords, see below:
![grafik](https://github.com/user-attachments/assets/0a669218-1ece-4d78-bfc2-791eae9f197f)

Hopefully it will be easy to improve this, thanks in advance!

**Comment by olvidalo** [comment]
Thanks for reporting! This has been fixed in the current release.
