### ISSUE TITLE
Idea: Section Headers

### ISSUE THREAD

**Issue by radeonthe1st** [olvidalo/obsidian-chord-sheets#9]
Hello there!

First of all, let me congratulate you on such an amazing plugin you are building. I am currently using Obsidian to teach my gf some guitar basics and this comes really really handy.

However, as I was laying down the chords of a song we both like, I just thought that it would be cool if there could be a way to separate different song sections. If I recall correctly, I think [the Chordlyrics plugin](https://github.com/nevernotmove/obsidian-chordlyrics?tab=readme-ov-file#headers) currently supports something like that, but I figured it wouldn't hurt to recommend including some feature similar to that.

Aside from that, the only way to do something like that would be to separate different chord blocks on different markdown sections, right?

Also, I think it would be cool to have some place to put annotations like "Capo 2nd fret" or specifying tuning, but I get that perhaps it could be dealt with outside of the chord block, just throwing an idea.

Anyway, thought you'd appreciate the feedback, and keep on with the great work you are putting out there!

**Comment by olvidalo** [comment]
I have added support for header highlighting in the latest release. Colors, font weight and font size for headers can be customized with [Style Settings](https://github.com/mgmeyers/obsidian-style-settings).

![image](https://github.com/user-attachments/assets/41dd8cd3-21c4-405d-9832-fdffe010f00e)

If you need more styling or visible section breaks, for now I'd say breaking them up into different chord blocks is the way to go, to keep the rendering logic simple and robust.

Regarding annotations: I would like to keep sheet parsing as compatible with the largest number of chord sheets found in the wild as possible. Section headers in square brackets are used a lot an seem to have become something like a common syntactical convention in chord sheets, while I'm not aware of something widely-used for annotations.
